FROM alpine
RUN apk update && \
    apk add openjdk11 && \
    apk add wget && \
    apk add git
WORKDIR /opt
RUN wget https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz && \
    tar -zxvf apache-maven-3.9.6-bin.tar.gz && \
    rm apache-maven-3.9.6-bin.tar.gz && \
    mv apache-maven-3.9.6 maven396 && mkdir /jobs
WORKDIR /jobs
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk
ENV M2_HOME=/opt/maven396
ENV PATH=${M2_HOME}/bin:$PATH
